### PR TITLE
update hungarian translate

### PR DESCRIPTION
**Pull request by benjoe1**

### CODE REVIEW

**Comment by bgcngm** [comment]
Merged manually.

**Comment by bgcngm** [comment]
I really advise you to erase your repo and re-fork the official one. You are messing up the file and is being really hard to merge. Please don't force us to have double work.

**Comment by benjoe1** [comment]
Previously I sent xml file (also this one) for C3C076 on xda forum. He asked me to use Github. There was a really old version of values-hu for Jellybean here, so I delete all strings and manually copy and paste it from a good xml file because I don't want to check it row by row.
What was the problem with it? Anyway the merge was wrong, there are some missing row. I will completely check it at home.

**Comment by bgcngm** [comment]
There could be some missing lines because I have only added from 869 line on. Try to revise only the lines that need to be changed and be careful about indentation (use space instead of tab).

**Pull request closed without merging**
