### PR TITLE
make TrafficMeter exclude traffic from loopback and TUN interfaces

### PR DESCRIPTION
**Pull request by dantmnf**
If a local proxy or VPN is used, there will be some traffic in lo and tunX interface. However, Android TrafficStats does not exclude them. Now I read statistics from kernel and excluded them.

PS. there are also same changes for KitKat and Marshmallow in my fork

### CODE REVIEW

**Comment by dantmnf** [comment]
missing some `import`s, closing.

**Comment by dantmnf** [comment]
fixed, reopening.

**Comment by C3C0** [comment]
Closed by https://github.com/GravityBox/GravityBox/commit/810dddecc7bc6e9310df4b94899683bd7197e2b2

**Comment by C3C0** [comment]
Further improvements made in this commit: https://github.com/GravityBox/GravityBox/commit/52bb1cc1cb95d625431e1bed4344bc3887be5ebf

**Pull request closed without merging**
