### PR TITLE
Better abbreviation for minutes : "min"

### PR DESCRIPTION
**Pull request by ch-vox**
IMHO, "min" stands for minutes abbreviation instead of "m". Otherwise it could translatable ?

### CODE REVIEW

**Comment by ch-vox** [comment]
Does this commit solve the abbreviation little issue ?

**Comment by C3C0** [comment]
Yes

**Comment by ch-vox** [comment]
k, thanks

**Comment by bgcngm** [comment]
I think it would be better to make it a translatable string. While in Portuguese, French and many European languages  its abbreviation is correct as "min", in some others (maybe Chinese, for example) it may not.

**Comment by ch-vox** [comment]
So should I close this pull request now if you make it translatable ?

**Comment by bgcngm** [comment]
Yes, we will make it translatable. I will close it.

**Comment by ch-vox** [comment]
thank you

**Pull request closed without merging**
