### PR TITLE
Update for strings.xml of hungarian trasnlation

### PR DESCRIPTION
**Pull request by benjoe1**
I hope, it will be without mistake of editing.

### CODE REVIEW

**Comment by bgcngm** [comment]
Again: 981 additions, 943 deletions not shown

If I accept this now, in the future will you add/change just the lines that matter? Because if you keep replacing the whole file, it will always look that you're modifying all lines.

**Comment by benjoe1** [comment]
Sorry. Yes, I just push the edit button and after send pull request.How I can make modification just for the new or changed strings?

**Comment by bgcngm** [comment]
Well, simply click "edit" button and then only make changes were changes have to be made (either by correcting existing translations or adding new ones).

EDIT: I will accept it as it is now, but in the future try to send it correctly.

**Comment by benjoe1** [comment]
Yes, I did exactly the same as you wrote. I pushed the edit button on strings.xml from here, and correct some text and put the translation of the new strings and pushed Propose File Change button, so I didn't make any change of the other text.

**Comment by bgcngm** [comment]
Something must have changed because 981 additions and 943 deletions were detected. Doesn't matter anymore. Let's hope the next updates are okay.

**Pull request merged**
