### PR TITLE
Updated French translation [KK]

### PR DESCRIPTION
**Pull request by ch-vox**
ModLockscreen: added option for double-tap to sleep on unlock ring
BatteryInfoManager: added option for charger plugged/unplugged sounds
ModStatusBar: added long-press action to notification panel clock
QS Tiles: make labels consistent with those in AOSP
QS Tiles: added tile for toggling Smart Radio feature on/off
GB Actions: added shortcut for toggling Smart Radio feature on/off
ModVolumePanel: Option to disable volume adjust vibrate
Added title line for master switches
ScreenRecording: option to use stock binary instead of alternative
ModStatusbar: added master switch for Clock settings
Clock: added option for controlling day of week size
Clock: added option for controlling AM/PM size
ModNavigationBar: option to disable navigation bar ring

### CODE REVIEW

**Comment by ch-vox** [comment]
Still in holidays (39°C in here), but I need to make a break with moutain climbing and beach tanning... :-P 
Regards

**Comment by C3C0** [comment]
Thanks :) and have a great time!

**Comment by ch-vox** [comment]
thank you !
just for fun, while mountain climbing on the vulcain, one chameleon was looking back at me... 

p1150705-small

**Comment by C3C0** [comment]
Omg. This is awesome :)

**Pull request merged**
