### PR TITLE
Updated French translation

### PR DESCRIPTION
**Pull request by ch-vox**
Added QuickSettings management master switch

### CODE REVIEW

**Comment by bgcngm** [comment]
Thanks, I'm going to cherry-pick this commit to JB branch, so you can also update translations there when done.

**Comment by ch-vox** [comment]
OK ;)

**Comment by bgcngm** [comment]
Maybe you forgot, but I have cherry-picked this commit and French translations to JB branch are up-to-date.

**Comment by ch-vox** [comment]
Oops ! Effectively, I've forgot to keep an eye on it. 
Thank you for making the job.
Regards

**Pull request merged**
