### PR TITLE
User can enter a hex-code string into GB's varous intents' extra fields.

### PR DESCRIPTION
**Pull request by alogblog**
In GB, all color codes are represented with 4bytes integer, which is SIGNED value.

For example, 100% opaque white color's code has 0xFFFFFFFF, which is -1 in decimal, not 4294967295 = 2^32-1.
So if user want 100% opaque white color, he has to write -1 in intent's related extra field. Of course this conversion is not impossible, but I think it's not user-friendly, and not directly usable from value taken from GB's cololr-pickers.

This little modification allows user to enter "#FF00FF00"-like-string format directly into intent's extra fields.

Adpapted extra color fields.

[NaviBar]
EXTRA_NAVBAR_BG_COLOR
EXTRA_NAVBAR_KEY_COLOR
EXTRA_NAVBAR_KEY_GLOW_COLOR
[StatusBar]
EXTRA_SB_BG_COLOR
EXTRA_SB_ICON_COLOR
EXTRA_SB_ICON_COLOR_SECONDARY
EXTRA_SB_DATA_ACTIVITY_COLOR
EXTRA_SB_DATA_ACTIVITY_COLOR_SECONDARY
[Notificafion]
EXTRA_BG_COLOR
[Pie]
EXTRA_PIE_COLOR_BG
EXTRA_PIE_COLOR_FG
EXTRA_PIE_COLOR_OUTLINE
EXTRA_PIE_COLOR_SELECTED
EXTRA_PIE_COLOR_TEXT

For example if we want to have 100% opaque green naviBar background,
send intent filled with,
action = "gravitybox.intent.action.ACTION_NAVBAR_CHANGED"
extra = "navbarBgColor:#ff00ff00"

### CODE REVIEW

**Comment by C3C0** [comment]
Too large change to be evaluated for merging into todays release. Keeping open for now.

**Comment by alogblog** [comment]
[Memo]
In color code, "#" character is required, ie "#FF000000", not just "FF000000".
In Tasker or other apps, users' extra fields are entered as STRING, and parsed as its form.
For example, extra is a form iike "bgColor:99000000", then Tasker makes it Int type extra.
"bgColor:true" --> boolean type extra, "bgColor:abcd" --> string type extra.

So in order to prevent it being parsed as interger in some case(all numberic color code), I prefixed "#" character in extra.

[Intent Info]

action = "gravitybox.intent.action.ACTION_NAVBAR_CHANGED"
extra = "navbarKeyColor:#ffffffff" (opaque white)
extra = "navbarBgColor:#ffffff"
extra = "navbarKeyGlowColor:#ffffff"

action = "gravitybox.intent.action.STATUSBAR_COLOR_CHANGED"
extra = "bgColor:#ffffffff"
extra = "iconColor:#ffffffff"
extra = "iconColorSecondary:#ffffffff"
extra = "dataActivityColor:#ffffffff"
extra = "dataActivityColorSecondary:#ffffffff"

action = "gravitybox.intent.action.NOTIF_BACKGROUND_CHANGED"
extra = "bgColor:#ffffffff"

action = "gravitybox.intent.action.PREF_PIE_CHANGED"
extra = "pieColorBg:#ffffffff"
extra = "pieColorBg:#ffffffff"
extra = "pieColorOutline:#ffffffff"
extra = "pieColorSelected:#ffffffff"
extra = "pieColorText:#ffffffff"

**Comment by alogblog** [comment]
extra = "iconColorSecondary:#ffffffff"
extra = "dataActivityColor:#ffffffff"
extra = "dataActivityColorSecondary:#ffffffff"

In my phone's GB, I couldn't find these color option in menu, and I don't know what secondary color is.
But according to source, I applied all(?) user-intent-able color codes.

**Comment by C3C0** [comment]
Thinking about it once again. This is something very special which requires certain level of user knowledge (tasker, defining intents). It is expected that if user can manage tasker and intents he is also able to manage integer representation of colors.

Anyway, if you insist on having this merged, some work still needs to be done.
1) Rebase on top of current KitKat branch
2) Instead of using redundant try/catch code everywhere for parsing color extra, make one function in Utils class (e.g. public static int parseColorExtra(String extra)) which will parse passed extra and return  integer representation. This would make it more modular.

**Comment by alogblog** [comment]
Yes your saying may be right. Tasker user could do it although some steps are required.

I dont insist on merging :)

1) Rebase... <-- I don't know that...I'm very novice git user.
2) I don't care whether you will accept mine or not, or you will apply other method like Utils class.

Because I(and other Tasker) user can convert hex to unsigned integer... I think it is absolutly just one option.

Thanks.

**Pull request closed without merging**
