### PR TITLE
Dutch strings reworked and completed

### PR DESCRIPTION
**Pull request by Martinusbe**

### CODE REVIEW

**Comment by bgcngm** [comment]
Thanks. You say completed, but there's much more to translate. Check against default strings .xml file.

**Comment by Martinusbe** [comment]
Okay ;-)
I may have time over the weekend.

**Comment by bgcngm** [comment]
Please pay more attention to the base you are using for the translations. I had to fix NL file because there were deprecated strings (45ca7f5384de7d1682c03dfb1a97c98d0f1478b4). :+1: 

Always use the latest version of res/values/strings.xml as base.

**Comment by Martinusbe** [comment]
Sorry,
I just took the strings from values-nl
I will be more careful in the future....

**Pull request merged**
