### PR TITLE
Updating Russian

### PR DESCRIPTION
**Pull request by gaich**

### CODE REVIEW

**Comment by bgcngm** [comment]
Thanks. It seems that indentation is wrong. Can you double check?

**Comment by gaich** [comment]
Sorry, I found three lines that weren`t in their places. Corrected.

**Comment by gaich** [comment]
The second commit is right. Or should I close this pull request and create another?

**Comment by bgcngm** [comment]
Right now I can't merge just the good one. Please create another patch with everything fixed (also for KK branch).

**Pull request closed without merging**
