### PR TITLE
Updated translation for Traditional Chinese (zh-rTW) (KK branch)

### PR DESCRIPTION
**Pull request by mo-504**

### CODE REVIEW

**Comment by mo-504** [comment]
@bgcngm what is the tab size used in the XML files? I may have messed up a bit so the layout may look wrong.. Sorry

**Comment by bgcngm** [comment]
We don't use tabs, but spaces instead.

**Comment by bgcngm** [comment]
Merged manually: b9001bcae6e94b03ecdaff1dfcad4406f7ad32f8. Fixed indentation and XML errors.

**Comment by mo-504** [comment]
@bgcngm so 4 spaces as indentation?

**Comment by bgcngm** [comment]
Exactly, 4 spaces.

**Comment by mo-504** [comment]
Thanks.
I will edit the preference of my editor to follow the style in XML. :D

**Comment by bgcngm** [comment]
Thanks. ;)

**Pull request closed without merging**
