### PR TITLE
Updated Portuguese [BR] Translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by bgcngm** [comment]
Thanks! Are you going to work on the missing translations?

Do you want me to update kitkat branch based on your translation or will you also update and send a pull request?

**Comment by ghost** [comment]
I'll work on the missing translations later. I send a request when it's 100%. Ok?

**Comment by bgcngm** [comment]
Sure, no worries!

**Comment by bgcngm** [comment]
Lara, just wanted to let you know that I have pushed a commit (931cba662862865d99272827c990a22dce505483) with fixes to the translation. First there was an error in the XML file and then I changed some strings to make texts coherent with existing ones.

**Pull request merged**
