### PR TITLE
Brazil Portuguese Translation

### PR DESCRIPTION
**Pull request by wyghor**
Upadate pt-BR

### CODE REVIEW

**Comment by bgcngm** [comment]
Thanks! You did it. =)

(Excelente trabalho)

**Comment by wyghor** [comment]
Thanks!

**Comment by bgcngm** [comment]
Just one thing... Did you make the translation based on mine (pt-PT)? I have noticed some words that were not supposed to be spelled that way (e.g. "aplicações" instead of "aplicativos"). Do you want me to fix those errors?

**Comment by wyghor** [comment]
was made at its base. I'll fix

**Comment by bgcngm** [comment]
No need, I can fix it quickly. Already did it for JB branch.

**Comment by wyghor** [comment]
perfect, thank you!

**Comment by bgcngm** [comment]
Done (9b8b1562f1f0271171987913ffa40d7533ddd051). Now sync your repo to make sure that you are always working on the latest version of the file.

**Pull request merged**
