### PR TITLE
ModLauncher: Hook DeviceProfile

### PR DESCRIPTION
**Pull request by theknut**
It's actually better to hook DeviceProfile. You can hook the DeviceProfile constructor which has cols and rows as parameters in it's method interface. This way you can change the values with param.args[x] instead of actually knowing the name of the variable.

With GNL being obfuscated now you only need to know the name of the DeviceProfil class if you use my approach. You can easily find the class by searching for "All Device Profiles must have an odd number of hotseat spaces" which is a [RuntimeException](http://androidxref.com/4.4.2_r1/xref/packages/apps/Launcher3/src/com/android/launcher3/DynamicGrid.java#103) thrown in this class.

You can find the source code of DeviceProfile on [Android XREF](http://androidxref.com/4.4.2_r1/xref/packages/apps/Launcher3/src/com/android/launcher3/DynamicGrid.java#54).

I haven't been able to test it since GB refused to launch "GravityBox System Framework is not responding". But it should work and it's the same implementation used in [Xposed GEL Settings](https://github.com/theknut/XposedGELSettings/blob/master/src/de/theknut/xposedgelsettings/hooks/Homescreen/DeviceProfileConstructorHook.java#L14).

I also added [Trebuchet](https://github.com/CyanogenMod/android_packages_apps_Trebuchet/blob/cm-11.0/src/com/android/launcher3/DynamicGrid.java#L57) as it's using the same launcher base. If you keep it, make sure to also edit the strings for the settings fragment.

### CODE REVIEW

**Comment by C3C0** [comment]
Thanks! 
I will have to merge manually since it looks like you use different code formatting

**Comment by theknut** [comment]
I used Eclipse's Ctrl + I for indents and Ctrl + Shift + F for formatting.

However it'll at least save you the time to search for the two variables
"numColumns" and "numRows". The only one to search for is the DeviceProfile
class which is pretty easy to find.
Glad I could contribute!

**Comment by C3C0** [comment]
Appreciated.
Btw, in GB we use spaces instead of tabs for indentation. Tabs are prone to different interpretation on different OS platforms thus can break merging process bad.

**Comment by theknut** [comment]
If you give me code style preference, I'll fix it for you.

**Comment by C3C0** [comment]
Hmm. This seems to be working in different way. It changed the layout of app drawer and messed up layout of home screen. My main screen disappeared and have 3x2 grid now

**Comment by theknut** [comment]
Okay, thats weird. I apologize.
Yes the app drawer grid is related to the homescreen layout. Can you try
changing the values in the afterHookedMethod? As I said, I wasn't able to
test it. But thats weird, as it's the current implementation in XGELS. How
can I avoid the GB framework check? It always fails on my CM build I use
for testing.

**Comment by C3C0** [comment]
And my screens are now gone forever :) I have to set them up again...
I think I rather skip this change as it might do the same for the users and they won't be probably happy about setting their launcher screens again. Previous version works, anyway.

But, thanks anyway

**Comment by theknut** [comment]
Yes, I remember having the same issue when I wrote the implementation some
months ago. However, once it's working I never had that issue.

But no worries, you can skip it. I don't understand why it's not working
for you though. If you look at the source code it's basically the same. One
last try could be to make the tweaks in the second DeviceProfile
constructor and change them in the afterHookedMethod. That's after all the
values have been calculated.

**Pull request closed without merging**
