### PR TITLE
Recents panel: Clear all in navigation bar / pie

### PR DESCRIPTION
**Pull request by SilentException**
Here is a mod that shows clear all button as a part of navigation bar and pie (replaces recents button when recents panel is shown). Both single tap and long press handlers are implemented and follow the existing GB logic. The general idea and drawables used are from PA.

BTW, together with my last pull request, these are my first steps in Android/Java programming so let me know if I should fix something or do anything in a different way or... :)

### CODE REVIEW

**Comment by C3C0** [comment]
Thanks. Will be reviewed and potentially merged in v3.0
One initial suggestion. I see you added a broadcast receiver in ModClearAll. Since recents dialog is a standard activity which is not always there, we should make sure to unregister receiver when activity is destroyed to avoid receiver leaks.

**Comment by SilentException** [comment]
I have pushed fix for BroadcastReceiver thing you noticed. At first I added clearAll public static method. But, when calling ModClearAllRecents.clearAll from ModHwKeys, static variable mRecentsPanelView was always null and the method was failing, calling clearAll from ModClearAllRecents worked fine. I couldn't understand why this is.

**Comment by C3C0** [comment]
Yeah. Thanks. I see a room for improvements. I don't think we need to mediate actions via modhwkeys at all. Navbar, recents and pie are running within the same package. So it might be easier to simply do some direct method calls. I'm about to start something new for 3.0 so I will start dealing with this one in more detail after I'm finished.

**Comment by SilentException** [comment]
Custom Navbar single tap and long press actions are initiated in ModHwKeys so not sure how to go around it at this point. Hope you'll find time to return to this one. Thank you!

**Comment by C3C0** [comment]
Squashed, revised and merged manually.
See commit: https://github.com/GravityBox/GravityBox/commit/c49a4258b87c1b1a5f28dbf04e8feba720bf0260

**Comment by C3C0** [comment]
Just FYI, one more fix was needed.
See commit: https://github.com/GravityBox/GravityBox/commit/6800d7c59968136e510ed5bca6cfcad55040dfce

**Comment by SilentException** [comment]
I have read the commit messages and will look at the code later on to see what I messed up. I warned i was a Android/Java noob, this was my first thing written :D

As I did my testing on a emulator, it was hard to notice the second bug (never rotated TBH). I've however encountered first bug (returning to recents) but thought it might be related to mouse click events and emulator, ooops.

Thanks once again and I will certainly take a look at the code to learn for the future.

**Comment by C3C0** [comment]
No problem. The second one is an edge case that's hardly reproducible on emulator.
I came across them while doing some intensive tests on a real device.

**Pull request closed without merging**
