### PR TITLE
Update Portuguese [BR] translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
up to 100%

**Comment by bgcngm** [comment]
Still missing strings from  to  sections.

**Comment by ghost** [comment]
Are you sure? I based on last res/values/strings.xml and it seens that nothing is missing in my comparation.

**Comment by bgcngm** [comment]
Totally sure. You did well on kitkat branch, but for some reason you forgot to complete it on jellybean branch.

**Pull request merged**
