### PR TITLE
ModExpandedDesktop: Use reflection to call methods in PhoneWindowManager

### PR DESCRIPTION
**Pull request by romracer**
This resolves an issue with some devices (Moto) that extend PhoneWindowManager into PhoneWindowManagerWithPartialDisplay and cause Xposed helpers to try and call the wrong method otherwise.

### CODE REVIEW

**Comment by C3C0** [comment]
And finally, I have prepared a list of places where we probably have the same issue. Please, could you also look into those when you have time? Thanks.
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L490
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L577
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L587
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L603
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L1147
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L1155
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L1217
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L1283
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L1289
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L1559
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L1569

**Comment by romracer** [comment]
I added a log statement to isKeyguardShowing's catch block and definitely got spammed.  I also noticed getStatusBarService in expanded desktop, which is one of the ones you listed above in ModHwKeys too.  I added both and I'll start looking at ModHwKeys.  Not sure I'm familiar with that part of GB but I'll take a peek.

**Comment by C3C0** [comment]
Thanks. ModHwKeys is a central place for "Navigation key actions" and GravityBox Actions.

**Comment by romracer** [comment]
I'm trying to make sure I'm testing this right since I don't use this section much (I do use long press back to kill).  I enabled debug in the ModHwKeys class and have been testing various actions using my recents key or volume rockers.  But if there was a problem, wouldn't I be catching exceptions almost right off the bat at:

https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L490

That's within the initZygote which has a catch block that logs exceptions.  I'm not seeing any.

I do notice these two use "param.thisObject" instead of mPhoneWindowManager:

https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L577
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModHwKeys.java#L587

But I don't know if I can trigger KEYCODE_SOFT_LEFT.  That's my back button and its triggering BACK.

**Comment by C3C0** [comment]
KEYCODE_SOFT_LEFT is assigned to GB's Custom Key that can be enabled within Navigation bar tweaks. Processed here: https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModNavigationBar.java#L414

Yes, you are right about assumption that callMethod at L490 should derp according to experience we have with ExpandedDesktop. If it doesn't then it's kind of strange and question is, what could cause a different behavior. Maybe you could log actual class for param.thiObject (param.thisObject.getClass().getName()) as well as mPhoneWindowManager to see whether it's PhoneWindowManager or PhoneWindowManagerWithPartialDisplay.

**Comment by C3C0** [comment]
Another hint. In one of your earlier comments here: https://github.com/GravityBox/GravityBox/pull/1305#issuecomment-83111171
you mentioned that interceptKeyBeforeQueing is overriden in PartialDisplay extension. This means that maybe hook for this method in ModHwKeys is not executed at all since it is placed on super class. If overriden method doesn't call through super class implementation, this hook won't be probably triggered at all, which could explain why it doesn't derp at L490.
If hook is being executed you should be at least getting DEBUG message logged at L493 (on any navbar key press)

**Comment by romracer** [comment]
Ah, I hadn't used the Custom Key before.  Or maybe I did back in JB or so but its been a while.  That makes testing that section easier :)  Added a couple of debug statements to print class names.  Both of them are PhoneWindowManagerWithPartialDisplay.  And it seems the haptic feedback using param.thisObject works fine.  I'm not seeing any exceptions and I get vibrations if I long press the custom key for example.

PartialDisplay does override interceptKeyBeforeQueueing but its calling the super class's method first.  I use the long press back to kill and that's been working.  I am also seeing the debug lines from L493 (that's how I knew my back button was sending BACK instead of SOFT LEFT).

Here's the method.  getPartialDisplayService is the only other method and its private.  Its just returning ServiceManager.checkService("partial_display_service") 

``` java
  public int interceptKeyBeforeQueueing(KeyEvent paramKeyEvent, int paramInt)
  {
    int i = super.interceptKeyBeforeQueueing(paramKeyEvent, paramInt);
    IPartialDisplayService localIPartialDisplayService = getPartialDisplayService();
    if ((0x20000000 & paramInt) != 0) {}
    for (int j = 1;; j = 0)
    {
      if ((j == 0) && (paramKeyEvent != null) && (paramKeyEvent.getKeyCode() == 26) && (paramKeyEvent.getAction() == 0) && (localIPartialDisplayService != null)) {}
      try
      {
        localIPartialDisplayService.notifyPowerKeyWakeup();
        return i;
      }
      catch (RemoteException localRemoteException)
      {
        Slog.d("PhoneWindowManagerWithPartialDisplay", "remote exception for notifyPowerKeyWakeup");
      }
    }
    return i;
  }
```

**Comment by romracer** [comment]
IPartialDisplayService is under android.app in the framework and looks related to "Moto Display" or whatever they're calling it these days.  Its the feature where the screen is partially on for notifications (which is advantageous since its an AMOLED screen).  I'm not sure what the difference is between ModHwKeys and ModExpandedDesktop.  I wonder if its a bug (or "short-coming") in the Xposed helpers maybe?

**Comment by C3C0** [comment]
Strange. Looking at what could be different. One could be the fact that hooks in expanded desktop are method replacements while those in ModHwKeys are standard before/after hooks. This hypothesis could be easily confirmed by debugging " detectSwipe" hook within expanded desktop. There's a callMethod we forgot to change. This hook is in effect when left-handed navbar is enabled.

**Comment by romracer** [comment]
I'm getting a no such method here and Xposed is looking for it within PartialDisplay

https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModExpandedDesktop.java#L944

What about this one

https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModExpandedDesktop.java#L183

If I'm understanding right, that method is called when the expanded desktop is activated or its mode is changed.  But I don't get any exceptions from the catch at L232.

**Comment by C3C0** [comment]
I think I understand why. It's all about method visibility. Only public methods are accessible within PartialDisplay derivate. All other methods declared as private need to be called using our reflection workaround.

**Comment by romracer** [comment]
Ahhh, that could be! I am at lunch but I will see if I see the same in my android policy when I get back. Put in another one for line 944 and broke them out to a private method. Will submit that soon too

**Comment by C3C0** [comment]
Yeah, take your time. I'm 100% sure it is all about method visibility.

**Comment by C3C0** [comment]
Just for curiosity. This is why callMethod throws error. When looping through class hierarchy to find method, it takes into account private methods only for specified class. Private methods of all super classes are ignored:
https://github.com/rovo89/XposedBridge/blob/master/src/de/robv/android/xposed/XposedHelpers.java#L249

**Comment by romracer** [comment]
Yep, so it is.  It looks like that also means any methods that don't specify a modifier are also considered (such as getStatusBarService or keyguardOn).

**Pull request merged**
