### PR TITLE
Recents panel: Clear all in navigation bar / pie - fixes

### PR DESCRIPTION
**Pull request by SilentException**
I fixed clear all icon coloring in pie, improved icon alpha to better match AOSP icons.

### CODE REVIEW

**Comment by SilentException** [comment]
Added one more commit.

Hopefully fixed the sticky clear all icon, strange AOSP bugs with recents panel still remain but at least the recents button will stay functional at all times
Optimizations in additional Views created on recents panel - don't do it if not needed

**Comment by bgcngm** [comment]
This will not be merged directly. As you can see, the pull request is adding some unrelated commits. Don't you prefer to re-sync your fork and push a completely clean commit?

**Comment by SilentException** [comment]
There we go, all sorted :+1:

**Comment by SilentException** [comment]
Seems like Android needs some time to start processing ordered broadcasts. Weird. 
But, as it seems from my quick test, ordered broadcasts are not needed at all. I just replaced sendOrderedBroadcast with regular sendBroadcast() in my test build and haven't had any issues (regarding sticky clear all). I suggest you also try this on your build. I'll push the commit if you're satisfied with the results.

**Comment by C3C0** [comment]
I think I tried that before. But clear all button didn't survive rotation change. I am not able to debug it well. Rotation change brings some chaos in how things are processed

**Comment by SilentException** [comment]
In order to survive rotation change, ordered broadcasts are needed. I forgot that.

First thing for me was to fix sticky clear all. I did that with hooking activity onPause and onResume. After that, ordered broadcasts solved the rotation issue.

I'm afraid I don't have any other solutions for now.

**Comment by C3C0** [comment]
I think I found a solution which will solve 2 issues in one turn.
It will also eliminate AOSP bug which leaves recents panel open when activity is brought into front with navbar ring.
In onPause, timer will be launched which when expired, will finish recents activity.
onResume will destroy the timer. So when screen is rotated onPause and onResume are called in very short time preserving activity.

**Comment by C3C0** [comment]
Here it is. Seems to be working fine here.
https://github.com/GravityBox/GravityBox/commit/1d767f51fddd4a457860851186c137d42f0ced34

**Comment by SilentException** [comment]
Great! I'll test this ASAP.

But I think you closed this one maybe a bit soon. There is also first commit, which fixes the coloring of the clear all in Pie.

Also second commit has some ModClearAllRecents/ModNavigationBar refactorings I think are worth doing. For example:
- not creating the ImageViews if not needed (in onFinishInflate hook),
- related to that, mClearRecentsMode is calculated on showImpl hook
- all of ModNavigationBar modifications (excluding ordered broadcasts).

**Comment by C3C0** [comment]
Yeah. But better to cherry pick them instead of merging directly.

**Comment by SilentException** [comment]
If you want, I could also resync and make another pull req.

**Comment by C3C0** [comment]
One already there. https://github.com/GravityBox/GravityBox/commit/6a6f96d8b5107fc2d2b92013675022b597ee7d24

**Comment by C3C0** [comment]
The second one, too: https://github.com/GravityBox/GravityBox/commit/245790137ef6771a521bce20ef970ec9ecccc2d7

**Comment by SilentException** [comment]
Thanks!

**Comment by SilentException** [comment]
Working good. Great job! Maybe just a smaller timer delay (300-400ms)?

One AOSP bug still remains after you start application from recents. If you open recents after app has loaded, the newly started app will not be visible in recents. Not sure what in AOSP source causes this behavior, maybe if we knew what causes it, with right hooks it would be possible to fix?

But, I will also try to make a screen cast of this and report the issues to Android issue tracker.

**Pull request closed without merging**
