### PR TITLE
Updated german translation for 3.0.0

### PR DESCRIPTION
**Pull request by LibertyMarine**
Hey,
Here's my translation for the newest translation, I only added the translated changes from 3.0.0
I hope the format is correct and I'd also be willing to contribute to future translations.

If that's OK for you ;)
I'm 1/2 Swiss and 1/2 German and I have many years of English experience... so I think I've got enough translation skills. (At least I hope so)

Have a great week,
LibertyMarine

### CODE REVIEW

**Comment by bgcngm** [comment]
Thanks!

**Comment by Minty123** [comment]
Hello LibertyMarine!

I'm also a German translator and have done most of the current translation. It seems like I can only contact you through comments...
If you like, we could help each other with the translation to make it as good as possible and to find a consistent translation style. :-)

Hope to hear from you soon!

Greetings
Minty

**Comment by LibertyMarine** [comment]
Hey,

Yeah, that's a good idea. I'm all for that. A question: How are we gonna exchange our translation files before we make a pull request?

LibertyMarine

**Comment by C3C0** [comment]
What about creating an organization with both of you as members and forked GB you can both push commits to?

**Comment by Minty123** [comment]
Hey Liberty!

I saw that I'm now in the GermanGravityBox organization. I'm not really used to GitHub yet so I might need to get into it a bit. Anyways, just send me an email (You can find the address on my profile.) Then we can work everything out a bit more in private.

By the way, thanks C3C0 for the suggestion. :-)

Greets
Minty

**Comment by LibertyMarine** [comment]
Yeah, I think that's a good idea. I'm neither used to GitHub. So for the beginning, I think it's a good idea but after some time we might change to GitHub so it's more transparent and easier for others to participate too.

But for the beginning that's fine :D

Thanks C3C0 and Minty123,

LibertyMarine

**Pull request merged**
