### PR TITLE
Extend Lenovo support

### PR DESCRIPTION
**Pull request by mrjavum**
Extend Lenovo devices support and fixing some Lenovo specific bugs.

### CODE REVIEW

**Comment by C3C0** [comment]
Nice. Looks good to me. Thanks.
I'll let Bruno to revise and possibly merge.

**Comment by bgcngm** [comment]
Nicely done. I'll merge it as soon as possible.

**Comment by bgcngm** [comment]
Quick question: is there any ROW version of a VIBE ROM? If not, you basically just want to check whether ROM is ROW or VIBE, correct?

**Comment by mrjavum** [comment]
Yes, there are 4 versions of 4.2 ROMs for now:
- Usual: CN and ROW
- VIBE: CN and ROW

But they have some common bugs (bug with HOME button is common for usual ROW and VIBE ROW ROMs)

**Comment by bgcngm** [comment]
Okay, merged manually: be7eb60b0f56486f1766b968bf66f10f4ef45ac2, be7eb60b0f56486f1766b968bf66f10f4ef45ac2 and 19d3a27a755c9f908dc1f991bd4572e8355a10b4.

**Pull request closed without merging**
