### PR TITLE
Lockscreen: show pattern error

### PR DESCRIPTION
**Pull request by SilentException**
Option to hide red trail when wrong pattern is entered.

### CODE REVIEW

**Comment by C3C0** [comment]
Merged manually.
See commit: https://github.com/GravityBox/GravityBox/commit/f6352fcda6cdb3064a507ef631e35d70878752d3

**Comment by C3C0** [comment]
Just realized those try/catch blocks are not necessary as calls to those methods are done within main try/catch block...

**Comment by SilentException** [comment]
Thx! Yes, it's why I haven't added try..catch block in the methods. BTW, perhaps you should remove them;  in this case they are not needed and as I understand, exception handling does impact performance, but I don't know in what effect?

**Comment by C3C0** [comment]
I've heard that, too, but don't have a clue in what extent they affect performance. Too lazy to measure :)
Removed them.

**Pull request closed without merging**
