### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by ronin79**

### CODE REVIEW

**Comment by bgcngm** [comment]
What changes have you done exactly? It is strange, seems that you have almost replaced the complete file (932 additions and 867 deletions).

**Comment by ronin79** [comment]
Oh, sorry, i'm new here, about from line 878 but i edit some other lines too.

**Comment by C3C0** [comment]
Are you sure you are within a correct branch? Were those changes intended for JellyBean or KitKat?
Recommendation: only make additions/edits to the current version of XML. Don't replace whole file. You can avoid making a lot of mistakes or introducing obsolete strings that have been already removed.

**Comment by ronin79** [comment]
Thanks for correction and i am terribly sorry.

**Pull request closed without merging**
