### PR TITLE
Make color appear correctly on non-standard devices (240x240).

### PR DESCRIPTION
**Pull request by gerhardol**
Fix for http://forum.xda-developers.com/showpost.php?p=48731969&postcount=4938

### CODE REVIEW

**Comment by DevMar** [comment]
hi can you make this app compatible for Omate users? decompiling, change code in xml file and recompiling not works:( the recompiling app do not want install.

**Comment by gerhardol** [comment]
The patch was made for Omate TrueSmart and similar, Android 240x240 screen with 4.2.2.
There are a bunch of similar devices coming now, compare to Galaxy Gear but not locked down Android.
Many has MediaTek Soc and crappy ROMs, needing patches.
Most have two HW buttons.

This is one minor thing that need to be changed to be able to change the application.
I am looking into modifying more HW keys, maybe also overriding dual press.
For example to reassign the lower button to Back so it can be used in the application.
That is separate, this is just a sinmple UI patch.

Tested on the emulator, 240x240 and "Galaxy Nexus".
ADT do not display correctly, AS does though.

**Comment by DevMar** [comment]
how can i apply this patch in to the GravityBox?

**Comment by C3C0** [comment]
You'll have to wait until somebody takes a look at this and tests it. We are on a holiday now.
I personally would prefer if you maintained your own fork to those special devices, though.

**Comment by gerhardol** [comment]
I provided a special build with this patch, for DevMar.

This patch is generic and minimal and I see no problem to include it in main.
Of course it is up to GB project to decide what patches that are accepted.
But I will try to be in sync, I have no interest in a permanent fork.

Other patches I work on should also be generic, but those are quite extensive.
I really would like to make button remapping dynamic, like in Xposed Additions (Pro).

**Comment by C3C0** [comment]
Merged manually

**Pull request closed without merging**
