### PR TITLE
Updating Russian again

### PR DESCRIPTION
**Pull request by gaich**
I started to use this beautiful app lately, but noticed many errors in Russian translation, so I revised it and translated the untranslated strings. I`m translator from XDA (http://forum.xda-developers.com/show....php?t=2069390), my translations are here: https://plus.google.com/u/0/+DmitryGaich/about
Thank you for your app, hope, you will merge this request  to improve Russian translation. I just edited last strings according to your explanation in comments.

### CODE REVIEW

**Comment by bgcngm** [comment]
@C3C076, this may be better to cherry-pick in order to correct the spacing and indentation.

**Comment by gaich** [comment]
Everything was done according English strings original, spacings or other stuff left intact, just translated.

**Comment by bgcngm** [comment]
I'm not saying that translation is wrong. It is just the indentation and line spacing from this point forward: https://github.com/gaich/GravityBox/blob/94a891f728e98b76c2f13330f4fe4baeff453684/res/values-ru/strings.xml#L897.

**Comment by C3C0** [comment]
Merged manually. https://github.com/GravityBox/GravityBox/commit/510a0154170727e34efeea6472e2215abe798a80

**Pull request closed without merging**
