### PR TITLE
Improved translations

### PR DESCRIPTION
**Pull request by raphass**
Improved PT-BR translations.

### CODE REVIEW

**Comment by bgcngm** [comment]
Thanks! Please don't forget to update also JB branch.

**Comment by raphass** [comment]
Hello, buddy! May I simply copy and paste everything? If so, I'll do it right now. :)

**Comment by bgcngm** [comment]
Not exactly because there are differences between JB and KK branch.

**Comment by gaich** [comment]
What branch is the right one for JB - jellybean or jellybean-wip?

**Comment by bgcngm** [comment]
It is jellybean. The other one is temporary.

**Comment by gaich** [comment]
Thank you.

**Comment by gaich** [comment]
Cannot edit strings both in jellybean and jellybean-wip - some constant error when trying to propose file change....

**Comment by bgcngm** [comment]
Does it happen when creating the pull request? Don't know why, but try to sync your repo again.

**Comment by gaich** [comment]
Don`t know how, but finaly succeeded. Thank you.

**Pull request merged**
